# **Numpy Fundamentals**

Difficulty Level **Beginner**

### Introduction to Numpy

    1) Numerical Python
    2) Developed in 2005 by Travis Oliphant
    3) Lingua Franca for data exchange
    4) ndarray - a n-dimensional array 
    5) Numpy internally stores data in contigous block of memory
    6) Fast opertaions on entire arrays
    7) Reading/Writing array data
    8) Data should be in homogeneous (Same Type)
    8) Linear Algebra Opertations

### Numpy vs List of Python
Numpy is 100 times faster than python's list. We will analyze from an example.

In [1]:
import numpy as np
numpy_list = np.arange(1000000) # returns a array by default

In [2]:
p_list = range(1000000) # returns a list by default

In [3]:
%time for i in range(0,11): result = numpy_list * 2 # where %time is a magic function of jupyter notebook

Wall time: 47.6 ms


In [4]:
%time for i in range(0,11): result1 = [x * 2 for x in p_list] # where %time is a magic function of jupyter notebook

Wall time: 2.9 s


# Numpy Array Creation Functions/Methods and Attributes

In [5]:
z = np.zeros((3,3)) # zeros function accepts one parameter of tuple e.g np.zeros((no. of rows,no. of columns)). It will make a matrix of 3x3 with all 0's of float type.

In [6]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### There are several other data types exist e.g Float, Integer, and String etc. Numpy can also hold the string and integer array.

In [7]:
z.dtype # dtype returns the data type of elements of numpy array

dtype('float64')

In [8]:
type(z)

numpy.ndarray

In [9]:
z.ndim # ndim returns the dimensions of numpy array

2

In [10]:
z.shape # return the rows and columns any matrix has

(3, 3)

In [11]:
o = np.ones((5,5)) # ones function accepts one parameter of tuple e.g np.ones((no. of rows,no. of columns)). It will make a matrix of 5x5 with all 1's of float type.

In [12]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
o.dtype

dtype('float64')

In [14]:
o.ndim

2

In [15]:
o.shape

(5, 5)

In [16]:
# np.arange(10) function is used to generate the numbers from 0 (it is default value if not mention) to 10 like as python's range() function.
elements = np.arange(10)
# np.arange(11,20) function is used to generate the numbers from starting point 11 to ending point 20.
elemetns1 = np.arange(11,20)
# np.arange(1,100,10) function is used to generate the numbers from starting point 0 to ending point 100 with steps 10.
elements2 = np.arange(1,100,10)

In [17]:
elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
elemetns1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
elements2

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [20]:
test = np.array([range(10)]) # np.array function is used to convert the python's list into numpy array

In [21]:
test.dtype

dtype('int32')

In [22]:
np.empty((3,3), dtype=int) # Return a new array of given shape and type, without initializing entries.

array([[2097266, 3276835, 5308461],
       [5439599, 5242912, 6488161],
       [6619243, 2097268, 6488147]])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [25]:
v_arr = np.arange(25).reshape(5,5)

In [26]:
v_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
v_arr.T # it will give a transpose of the matrix means rows will be columns and columns will be rows

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [28]:
v_arr.ravel() # It will convert the 2d matrix view into vector but actually it will remain 2d matrix lets verify

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
v_arr.shape

(5, 5)

In [30]:
v_arr.size

25

In [31]:
np.ones_like(v_arr) # it will make an numpy array of same shape and dtype of v_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.linspace(1,100,10) # it will make a numpy array from 1 to 100 and give exactly 10 elements of equally differenced eachother.
# or we can say data it divide the 1 to 100 on exactly 10 equal parts.

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [33]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [34]:
v_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
arr1 = arr.flatten() # this function automatically makes a copy first then change the dimension and store into another variable.
arr1[0] = 25
arr1

array([25,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [38]:
arr.resize(4,4) # it will directly change the dimensions of original array and nothing return back.
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
arr.shape

(4, 4)

# Useful numerical methods of NumPy arrays

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.argmin(arr) # it will give the index of smallest number from the vector or matrix

0

In [42]:
arr.argmin(axis=0) # it will find the minimum number row wise and return the vector of indices from matrix

array([0, 0, 0], dtype=int64)

In [43]:
np.argmax(arr) # it will give the index of largest number from the vector or matrix

8

In [44]:
arr.max() # it will return the maximum element from the matrix

8

In [45]:
arr.max(axis=1) # it will find the maximum number column wise and return the vector of values from matrix

array([2, 5, 8])

In [46]:
arr.min() # it will return the minimum element from the matrix instead of its index

0

In [47]:
arr.mean() # it will return the average of the matrix

4.0

In [48]:
arr.sum() # it will return the sum of the matrix

36

# Arithmetic and Logical operations on ndarry

In [49]:
narr = np.arange(10)

In [50]:
narr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
narr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
narr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [53]:
narr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [54]:
narr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
(narr<5).any() # it will return true if any one element of the arr fulfil the condition arr<5

True

In [56]:
(narr<5).all() # it will return true if all the element of the arr fulfil the condition arr<5

False

In [57]:
narr%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [58]:
narr[narr%2==0]

array([0, 2, 4, 6, 8])

In [59]:
narr[narr%2!=0]

array([1, 3, 5, 7, 9])

# Statistical Operations on NumPy arrays

In [60]:
stat_arr = np.array([[0,2,4,6,8],[1,3,5,7,9]])
stat_arr

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [61]:
stat_arr.shape

(2, 5)

In [62]:
stat_arr.mean() # it will return the mean of the provided matrix

4.5

In [63]:
stat_arr.std() # it will return the standard devition of the provided matrix

2.8722813232690143

In [64]:
print(f"Sum of matrix is {stat_arr.sum()} and product of matrix is {stat_arr.prod()}") # it will give sum and product of matrix

Sum of matrix is 45 and product of matrix is 0


In [65]:
stat_arr.var() # it will return the variation of the matrix

8.25

# Indexing and Slicing

In [66]:
arr2d = np.arange(25).reshape(5,5) # reshape() is used to change the shape() of matrix in term of rows and columns

In [67]:
arr3d = np.arange(64).reshape(4,4,4)

In [68]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [70]:
arr2d[2,2] # simple indexing gives just the value

12

In [71]:
arr2d[[0,2,4]] # fancy indexing gives the multiple values even row or specific columns or all or selected rows

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [72]:
arr2d[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [73]:
arr2d[[0,2,4],[0,2,4]]

array([ 0, 12, 24])

In [74]:
arr3d[3,[0,2]] # selecting number of rows from 3d matrix using fancy indexing

array([[48, 49, 50, 51],
       [56, 57, 58, 59]])

In [75]:
arr3d[2,:,[0,2]] # selecting number of columns of all rows from 3d matrix using fancy indexing

array([[32, 36, 40, 44],
       [34, 38, 42, 46]])

## Slicing

In [76]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr2d[0:5:2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [78]:
arr2d[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [79]:
arr2d[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [80]:
arr2d[:,1:5:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [81]:
arr2d[2:3,:]

array([[10, 11, 12, 13, 14]])

In [82]:
arr2d[:,2:3]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [83]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [84]:
arr3d[0:4:2,0:4:2,:]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[32, 33, 34, 35],
        [40, 41, 42, 43]]])

In [85]:
arr3d[:,3:,:]

array([[[12, 13, 14, 15]],

       [[28, 29, 30, 31]],

       [[44, 45, 46, 47]],

       [[60, 61, 62, 63]]])

In [86]:
arr3d[0::3,:,3:]

array([[[ 3],
        [ 7],
        [11],
        [15]],

       [[51],
        [55],
        [59],
        [63]]])

In [87]:
arr3d[:,1:-1,1:-1]

array([[[ 5,  6],
        [ 9, 10]],

       [[21, 22],
        [25, 26]],

       [[37, 38],
        [41, 42]],

       [[53, 54],
        [57, 58]]])

# Stacking

In [90]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [98]:
print(np.hstack([arr1,arr2]))
np.hstack([arr1,arr2]).shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


(20,)

In [96]:
print(np.vstack([arr1,arr2]))
np.vstack([arr1,arr2]).shape

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


(2, 10)

In [100]:
arr2d1 = np.arange(15).reshape(5,3)
arr2d2 = np.arange(25).reshape(5,5)
print(arr2d1)
print(arr2d2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [102]:
np.hstack([arr2d1,arr2d2])

array([[ 0,  1,  2,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7,  8,  9],
       [ 6,  7,  8, 10, 11, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17, 18, 19],
       [12, 13, 14, 20, 21, 22, 23, 24]])

In [103]:
arr2d1 = np.arange(15).reshape(3,5)
arr2d2 = np.arange(25).reshape(5,5)
print(arr2d1)
print(arr2d2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [104]:
np.vstack([arr2d1,arr2d2])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [120]:
np.row_stack([arr1,arr2]) # same as np.vstack()

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [121]:
print(np.column_stack([arr1,arr2]).shape)
np.column_stack([arr1,arr2]) # stacking 1-D array as columns into 2-D array.

(10, 2)


array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])